# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c30a3ac2181550a2636208faef5f5107beb95de732314f888df8cf8f9a8df1827d26ba8673fd6f358175d11effaa93c1d31eea75bf5bfaa115647af8d132ac92

test:
  secret_key_base: ffb25266c235339a5d8cb77a157f1611f41cca416fdb3940a6f216aa9aa07569ebfd8e6f180e40d9cf0b81043007d23a6297a98da99c8f5f12bc884b81a02316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
